football/urls.py
from django.contrib import admin
from django.views.generic import TemplateView
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.documentation import include_docs_urls

from .views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include_docs_urls(title='Foot-AI API')),
    path('api/auth/', include('accounts.api.urls', namespace='api-auth')),
    path('api/user/', include('accounts.api.user.urls', namespace='api-user')),
    path('api/injuries/', include('injuries.api.urls', namespace='api-injuries')),
    path('api/players/', include('profiles.api.urls', namespace='api-players')),
    path('api/gps/', include('gps_data.api.urls', namespace='api-gps')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    re_path(r'^(?P<path>.*)', TemplateView.as_view(template_name='ng.html'), name='home'),
]

gps_data/urls.py
from django.urls import path
from .views import GpsDataListView, ChartsData

app_name = 'gps'
urlpatterns = [
    path('', GpsDataListView.as_view(), name='home' ),
    path('data/', ChartsData.as_view(), name='data' )
]

injuries/urls.py
from django.urls import path
from .views import InjuryDetailView, InjuryListView, InjuryCreateView

app_name = 'injuries'
urlpatterns = [
    path('list/', InjuryListView.as_view(), name='list' ),
    path('new/', InjuryCreateView.as_view(), name='new' ),
    path('<int:pk>/', InjuryDetailView.as_view(), name='detail'),
]

templates/base/css.html
 {% load static %}

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

<!-- Fontawesome CSS -->
<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' />

<!-- jquery-confirm CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">

<!-- Custom styles for this template -->
<!-- <link rel="stylesheet" href="{% static 'css/main.css' %}"> -->

<link rel='stylesheet' href="{% static 'css/reactify-django.ui.css' %}" />

templates/base/footer.html
<footer class="footer">
    <div class="container">
        <span class="d-flex justify-content-end p-0 m-0">FootBall AI &copy;</span>
    </div>
</footer>

templates/base/forms.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class='col-12 col-md-6 mx-auto'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form|cripsy }}
  <button type='submit' class='btn btn-default'>Save</button>
</form>
</div>
{% endblock %}

templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS
slim is missing ajax -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

<!-- jquery-confirm JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

<!-- js Render -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/jsrender/0.9.88/jsrender.min.js'></script>

<!-- Chart.js -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js'></script>

<!-- Materialize JS Compiled and minified JavaScript -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script> -->

 <!-- Icons -->
 <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>

 <!-- Footbal AI Main JS -->
<!-- <script src='{% static "js/football.main.js" %}'></script> -->
<script src="{% static 'js/reactify-django.ui.js' %}"></script>

<script>feather.replace()</script>

templates/base/navbar.html
{% url 'home' as home_url %} 
{% url 'injuries:new' as injuries_new %} 
{% url 'injuries:list' as injuries_list %} 
{% url 'players:new' as players_new %}
{% url 'players:list' as players_list %}
{% url 'gps:home' as gps_home_url %}

<nav class="navbar navbar-dark fixed-top my-navbar flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{{ home_url }}">Foot AI</a>
  {% if request.user.is_authenticated %}
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="{% url 'logout' %}">Sign out</a>
    </li>
  </ul>
  {% endif %}
</nav>
{% if request.user.is_authenticated %}
<div class="container">
  <div class="row">
    <nav class="flex-sm-column col-sm-2 d-none d-md-block bg-light sidebar">
      <a class="nav-link {% if request.path == home_url %}active{% endif %}" href="{% url 'home' %}">
        <span data-feather="home"></span>
        Dashboard</a>
      <a class="nav-link" data-toggle="collapse" href="#injuries">
        <span data-feather="alert-triangle"></span>
        Injuries
        <ul class="sidenav-second-level collapse" id="injuries">
          <a class="nav-link {% if request.path == injuries_new %}active{% endif %}" href="{% url 'injuries:new' %}">
            <span data-feather="user-plus"></span>
            New
          </a>
          <a class="nav-link {% if request.path == injuries_list %}active{% endif %}" href="{% url 'injuries:list' %}">
            <span data-feather="user-plus"></span>
            List
          </a>
        </ul>
      </a>
      <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse"
        href="#players">
        <span data-feather="users"></span>
        Players
        <ul class="sidenav-second-level collapse" id="players">
          <a class="nav-link {% if request.path == players_list %}active{% endif %}" href="{% url 'players:list' %}">
            <span data-feather="user"></span>
            List
          </a>
          <a class="nav-link {% if request.path == players_new %}active{% endif %}" href="{% url 'players:new' %}">
            <span data-feather="user-plus"></span>
            Add player
          </a>
        </ul>
      </a>
      <a class="nav-link {% if request.path == gps_home_url %}active{% endif %}" href="{% url 'gps:home' %}">
        <span data-feather="grid"></span>
        GPS
      </a>
      <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
        <span>Saved reports</span>
        <a class="d-flex align-items-center text-muted" href="#">
          <span data-feather="plus-circle"></span>
        </a>
      </h6>
      <ul class="nav flex-column mb-2">
        <li class="nav-item">
          <a class="nav-link" href="#">
            <span data-feather="file-text"></span>
            Current month
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <span data-feather="file-text"></span>
            Last quarter
          </a>
        </li>
      </ul>
    </nav>
  </div>
</div>
{% endif %}