football/urls.py
from django.contrib import admin
from django.views.generic import TemplateView
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.documentation import include_docs_urls

from .views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include_docs_urls(title='Foot-AI API')),
    path('api/auth/', include('accounts.api.urls', namespace='api-auth')),
    path('api/user/', include('accounts.api.user.urls', namespace='api-user')),
    path('api/injuries/', include('injuries.api.urls', namespace='api-injuries')),
    path('api/players/', include('profiles.api.urls', namespace='api-players')),
    path('api/gps/', include('gps_data.api.urls', namespace='api-gps')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    re_path(r'^(?P<path>.*)', TemplateView.as_view(template_name='ng.html'), name='home'),
]

profiles/urls.py
from django.urls import path
from .views import PlayerCreateView, PlayerDetailView, PlayerListView

app_name = 'profiles'
urlpatterns = [
    path('', PlayerListView.as_view(), name='list' ),
    path('new/', PlayerCreateView.as_view(), name='new' ),
    path('<int:pk>/', PlayerDetailView.as_view(), name='detail'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Foot AI</title>
    {% include 'base/css.html' %} {% block base_head %}{% endblock %}
</head>

<body>

        {% block content %}{% endblock %}


    {% include 'base/js.html' %} {% block javascript %} {% endblock %}
</body>

</html>

templates/home_page.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Overview</h1>
</div>
<div class="container">
  <div class="row">
    {% for player in high_risk %}
    <div class="col-sm-4">
      <div class="card b-1 m-2">
        <img class="card-img-top" src="{% if player.image %} {{ player.image.url }} {% else %} {% endif %}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">{{ player.first_name | capfirst }} {{ player.last_name | capfirst }}</h5>
          <p class="card-text">High Risk</p>
          <a href="{% url 'profiles:detail' pk=player.pk %}" class="btn btn-primary">Details</a>
        </div>
      </div>
    </div>
    {% endfor %} {% for player in med_risk %}
    <div class="col-sm-4">
      <div class="card b-1 m-2">
        <img class="card-img-top" src="{% if player.image %} {{ player.image.url }} {% else %} {% endif %}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">{{ player.first_name | capfirst }} {{ player.last_name | capfirst }}</h5>
          <p class="card-text">Medium Risk</p>
          <a href="{% url 'profiles:detail' pk=player.pk %}" class="btn btn-primary">Details</a>
        </div>
      </div>
    </div>
    {% endfor %} {% for player in low_risk %}
    <div class="col-sm-4">
      <div class="card b-1 m-2">
        <img class="card-img-top" src="{% if player.image %} {{ player.image.url }} {% else %} {% endif %}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">{{ player.first_name | capfirst }} {{ player.last_name | capfirst }}</h5>
          <p class="card-text">Low Risk</p>
          <a href="{% url 'profiles:detail' pk=player.pk %}" class="btn btn-primary">Details</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/ng.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Foot-AI</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:300,700" rel="stylesheet">
<link rel="stylesheet" href="{% static 'styles.css' %}"></head>
<body>
  <ngx-app></ngx-app>
<script type="text/javascript" src="{% static 'runtime.js' %}"></script>
<script type="text/javascript" src="{% static 'polyfills.js' %}"></script>
<script type="text/javascript" src="{% static 'main.js' %}"></script>
<script type="text/javascript" src="{% static '0.js' %}"></script>
<script type="text/javascript" src="{% static '1.js' %}"></script>
<script type="text/javascript" src="{% static '2.js' %}"></script>
</body>
</html>